### ISSUE TITLE
Add hook_help to the module

### ISSUE THREAD

**Issue by naveenvalecha** [honzapara/modifiers_vanta#1]

**Comment by honzapara** [comment]
Hi Naveen,

we've got quite a solid documentation already found here https://www.drupal.org/docs/contributed-modules/modifiers
There is no really module configuration for this. Only the paragraphs component. Maybe we could add at least the link over there, but I think it is not needed.

**Comment by naveenvalecha** [comment]
It's must-have for a contributed module

**Comment by honzapara** [comment]
Hi Naveen,

I added the help page for the module. Please review. https://github.com/honzapara/modifiers_vanta/commit/c6c4c3aa722d4bba89cd14f70782418a362693a9

**Comment by naveenvalecha** [comment]
Thanks! Good to go
