### ISSUE TITLE
Define the config schema/metadata of vanta_config

### ISSUE THREAD

**Issue by naveenvalecha** [honzapara/modifiers_vanta#3]
Define the config schema of vanta_config used in the project here https://github.com/honzapara/modifiers_vanta/blob/master/src/Plugin/modifiers/VantaModifier.php#L42

**Useful Links**

* https://www.drupal.org/docs/drupal-apis/configuration-api/configuration-schemametadata

**Comment by honzapara** [comment]
Hi Naveen,

there is no module-specific config. We've got only fields. We don't even have it for modifiers_pack.

**Comment by naveenvalecha** [comment]
> no module-specific config.

it could be closed then :)
